baseURL = 'https://whalien.space/'
languageCode = 'zh-cn'
title = "whalien's blog"
theme = 'github.com/whaliendev/hugo-theme-mini'
defaultContentLanguage = 'zh'
enableToc = true
showToc = true
math = true
paginate = 5
paginatePath = 'posts'
hasCJKLanguage = true
enableComments = true

[params]
Bio = "software engineer, dreams make the world a little better."

[services]
  [services.disqus]
    shortname = 'whalien-space'
